"""Typed data structures returned by the selfheal agent loop."""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class Attempt:
    """A single generate-run-(maybe fail) cycle in the self-healing loop.

    Attributes:
        code: The full Python source generated by Claude for this attempt.
        output: Captured stdout from executing ``code``.
        error: Captured stderr / traceback from executing ``code``. Empty
            string if the attempt succeeded.
        succeeded: Whether this attempt exited with code 0.
        exit_code: The subprocess exit code, or ``None`` if execution timed
            out before producing one.
        timed_out: Whether execution was killed for exceeding the timeout.
    """

    code: str
    output: str
    error: str
    succeeded: bool
    exit_code: int | None
    timed_out: bool = False


@dataclass
class RunResult:
    """The full outcome of a ``selfheal.run()`` call.

    Every attempt is preserved in ``attempts`` so callers (and the CLI/web
    demo) can inspect exactly how the agent arrived at its final answer.

    Attributes:
        task: The original plain-English task description.
        final_code: The code from the last attempt (successful or not).
        succeeded: Whether any attempt succeeded.
        attempts: Ordered list of every attempt made, oldest first.
        result_output: The stdout of the successful attempt, or the stderr
            of the final failed attempt if the agent never succeeded.
    """

    task: str
    final_code: str
    succeeded: bool
    attempts: list[Attempt] = field(default_factory=list)
    result_output: str = ""

    @property
    def num_attempts(self) -> int:
        """Number of attempts made before stopping."""
        return len(self.attempts)
